/*
 * 2006 (c) -={ MikeP }=-
 */


#include	"qxl_common.h"
#include	"qbase_client.h"





/* external variables */
extern pthread_mutex_t	EOD_mutex;
extern pthread_cond_t	EOD_cond;




/* All database connectivity */
QB_connid_t			TU_taxes;		/* we will get taxes and see how many they owe us */
Qbase_table_desc_t	*TUC_taxes;
uint32_t			TU_taxes_rowlen;
uint8_t				*TU_taxes_row;
double				*TU_montax;
uint32_t			TID;



QB_connid_t			TU_accounts;
QB_connid_t			TU_updacc;
Qbase_table_desc_t	*TUC_accounts;
uint32_t			TU_accounts_rowlen;
char				*TU_accounts_row;
char				*TU_updacc_row;

double				*TU_updacc_sum;
uint32_t			*TU_accounts_TID;
uint32_t			AID;



QB_connid_t			TU_payments;
Qbase_table_desc_t	*TUC_payments;
uint32_t			TU_payments_rowlen;
uint8_t				*TU_payments_row;

double				*TU_pay_sum;
uint32_t			*TU_pay_account;
uint32_t			*TU_pay_date;
char				*TU_pay_desc;









char				ylog_name[QBASE_TAB_NAMELEN]; /* the log table we need to manage */
extern struct tm	log_t_tm;
extern time_t		log_t_time;
int	mon_day[12] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};



FILE*	log_file;
int		l_accs;
int		l_paym;








/*
 * This function is executed each time the End Of Day (EOD) happens.
 * 
 * Right now it does the following:
 * 
 * I)	Takes monthly taxes of all the accounts.
 * II)	For the last day it calculates the amount of traffic,
 *		generated by each NIC, listed on the database and
 *		adds appropriate records in payments table.
 * III)	?.
 * IV)	?.
 * V)	?.
 * VI)	?.
 * VII)	?.
 * IIX)	?.
 * IX)	?.
 * X)	?.
 */

void * EOD_func(void *arg){
	
	/* USEFUL :) */
	QB_result_t		QXB_rslt;	/* QX-base results */
	uint32_t		ret_val;
	int				res;		/* System results */
	
	
	
	/* prepare connections */
	if( QBASE_E_OK != (QXB_rslt = Qbase_connect( QBASE_RM_PATH, &TU_taxes)) ){
		printf("TU_taxes: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_connect( QBASE_RM_PATH, &TU_accounts)) ){
		printf("TU_accounts: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_connect( QBASE_RM_PATH, &TU_updacc)) ){
		printf("TU_updacc: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_connect( QBASE_RM_PATH, &TU_payments)) ){
		printf("TU_payments: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	
	/* select tables */
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_select( TU_taxes, "taxes" ))){
		printf("TU_taxes: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_caps( TU_taxes, &TUC_taxes ))){
		printf("TU_taxes: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	TU_taxes_row = Qbase_row_newbuffer( TUC_taxes, &TU_taxes_rowlen );
	TU_montax = (double*)(TU_taxes_row + TUC_taxes->Fields[QXL_TAXES_MONTAX].Offset);
	
	/* Accounts */
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_select( TU_accounts, "accounts" ))){
		printf("TU_accounts: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_select( TU_updacc, "accounts" ))){
		printf("TU_updacc: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_caps( TU_accounts, &TUC_accounts ))){
		printf("TU_accounts: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	TU_accounts_row = Qbase_row_newbuffer( TUC_accounts, &TU_accounts_rowlen );
	TU_accounts_TID = (uint32_t*)(TU_accounts_row + TUC_accounts->Fields[QXL_ACCOUNTS_TAX].Offset);
	if( QBASE_E_OK != (QXB_rslt = Qbase_GetUpdateHeader( TUC_accounts, &TU_updacc_row ))){
		printf("TU_accounts: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	TU_updacc_sum = (double*)(TU_updacc_row + TUC_accounts->Fields[QXL_ACCOUNTS_SUM].Offset + TUC_accounts->FieldNum + sizeof(uint32_t));
	((uint8_t*)(TU_updacc_row + sizeof(uint32_t)))[QXL_ACCOUNTS_SUM] = QBASE_U_SUB;
	
	/* Payments */
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_select( TU_payments, "payments" ))){
		printf("TU_payments: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	if( QBASE_E_OK != (QXB_rslt = Qbase_table_caps( TU_payments, &TUC_payments ))){
		printf("TU_payments: %s\n", QBERROR[QXB_rslt]);
		exit(-1);
	}
	TU_payments_row = Qbase_row_newbuffer( TUC_payments, &TU_payments_rowlen );
	TU_pay_account	= (uint32_t*)(TU_payments_row + TUC_payments->Fields[QXL_PAYMENTS_ACC].Offset);
	TU_pay_sum		= (double*)(TU_payments_row + TUC_payments->Fields[QXL_PAYMENTS_SUM].Offset);
	TU_pay_date		= (uint32_t*)(TU_payments_row + TUC_payments->Fields[QXL_PAYMENTS_DPAY].Offset);
	TU_pay_desc		= (char*)(TU_payments_row + TUC_payments->Fields[QXL_PAYMENTS_DESC].Offset);
	
	
	
	
	
	
	/* open log file */
	log_file = fopen("/billing.log","a+");
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	pthread_mutex_lock( &EOD_mutex );
	
	while(EOK == pthread_cond_wait( &EOD_cond, &EOD_mutex )){
		
		/*
		 * I) Tax per month is payed daily
		 */
		{
			/* tell people what they pay for */
			strftime(ylog_name,QBASE_TAB_NAMELEN,"%F",&log_t_tm); /* table name is ISO date representation: YYYY-MM-DD */
			snprintf(TU_pay_desc,255,"Monthly tax. (payment for %s)",ylog_name);
			*TU_pay_date = log_t_time;
			
			/* reset taxes */
			Qbase_fetchrst( TU_taxes );
			l_accs = 0;
			l_paym = 0;
			
			/* select a tax */
			while( QBASE_E_OK == (QXB_rslt = Qbase_fetch(TU_taxes,TU_taxes_row,TU_taxes_rowlen)) ){
				
				double	pay_sum = mon_day[log_t_tm.tm_mon];
				TID = QXB_FV_UINT(QXL_TAXES_N, TUC_taxes, TU_taxes_row);
				
				/* do not add records for accounts having zero tax */
				if( *TU_montax == (double)0.00 ) continue;
				/* how much should they pay */
				pay_sum = (*TU_montax)/pay_sum; /* days in month */
				
				/* 
				 * for all accounts, having this tax - update accounts' sum
				 * and make a record in payments table.
				 */
				Qbase_fetchrst( TU_accounts );
				while( QBASE_E_OK == (QXB_rslt = Qbase_fetch(TU_accounts,TU_accounts_row,TU_accounts_rowlen)) ){
					
					if(TID == *TU_accounts_TID){
						/* this account is to be updated */
						
						l_accs++;
						
						AID = QXB_FV_UINT(QXL_ACCOUNTS_N, TUC_accounts, TU_accounts_row);
						*TU_updacc_sum = pay_sum;
						if( QBASE_E_OK != (QXB_rslt = Qbase_seek(TU_updacc,AID)) ){
							printf("ERROR account(%u): %s\n", AID, QBERROR[QXB_rslt]);
						}
						if( QBASE_E_OK != (QXB_rslt = Qbase_updcur(TU_updacc,TU_updacc_row)) ){
							printf("ERROR updating account(%u): %s\n", AID, QBERROR[QXB_rslt]);
						}
						/* Account is updated - add record to payments table */
						*TU_pay_account = AID;
						*TU_pay_sum = -(pay_sum);
						if( QBASE_E_OK != (QXB_rslt = Qbase_insert( TU_payments, TU_payments_row, TU_payments_rowlen )) ){
							printf("Insert payment: %s\n", QBERROR[QXB_rslt]);
						}
					}
					/* proceed to next account */
				}
				/* Proceed to next tax if any. */
				Qbase_flush(TU_payments); /* flush payments */
				Qbase_flush(TU_updacc); /* flush accounts */
			}
		} /* monthly taxes are done */
		
		fprintf(log_file,"EOD_payments: %i accounts updated.\n",l_accs);
		fflush( log_file );
		
		
		
		/*
		 * II) For each NIC count how much traffic costed client
		 * 		previous day and add appropriate record into database.
		 */
		
	}
	
	printf("Error waiting for condition: %s\n",strerror(errno));
	/* close all file descriptors */
	
	close( TU_taxes );
	close( TU_accounts );
	
	return;
}



